
 - os: linux
    compiler: gcc
    env: COMPILER=g++-6
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script:
- cmake -H. -B_builds
- cmake --build _builds
- cd _builds
- ./pack person1.yml
- cat person1.yml
